import bookImg1 from'../../src/Assest/bookImg/1book_img.jpg'
import bookImg2 from'../../src/Assest/bookImg/2book_img.jpg'
import bookImg3 from'../../src/Assest/bookImg/3book_img.jpg'
import bookImg4 from'../../src/Assest/bookImg/4book_img.jpg'
import bookImg5 from'../../src/Assest/bookImg/5book_img.jpg'
import bookImg6 from'../../src/Assest/bookImg/6book_img.jpg'
import bookImg7 from'../../src/Assest/bookImg/7book_img.jpg'
import bookImg8 from'../../src/Assest/bookImg/8book_img.jpg'
import bookImg9 from'../../src/Assest/bookImg/9book_img.jpg'
import bookImg10 from'../../src/Assest/bookImg/10book_img.jpg'
import bookImg11 from '../../src/Assest/bookImg/Image.png'
import bookImg12 from '../../src/Assest/bookImg/Image 36.png'
import bookImg13 from '../../src/Assest/bookImg/Image 7.png'
import bookImg14 from '../../src/Assest/bookImg/Image 12.png'
import bookImg15 from '../../src/Assest/bookImg/Image 13.png'
import bookImg16 from '../../src/Assest/bookImg/Image 14.png'
import bookImg17 from '../../src/Assest/bookImg/Image 18.png'
import bookImg18 from '../../src/Assest/bookImg/Image 23.png'

export const bookImg=[bookImg1,bookImg2,bookImg3,bookImg4,bookImg5,bookImg6,bookImg7,bookImg8,bookImg9,bookImg10,bookImg11,bookImg12,bookImg13,bookImg14,bookImg15,bookImg16,bookImg17,bookImg18]